name: Wake Up Render
on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render URL
        run: curl -f -s https://mern-todo-o78t.onrender.com/health